version: '3.1'
services:
    meedu:
        image: "dongcj/meedu"
        restart: always
        container_name: meedu         
        networks:
            - frontend
            - backend
        ports:
          - 3003:80 
        volumes:
          - /opt/meedu/code:/meedu          
        depends_on:
          - mysql
    meedu-mysql:
        image: "mysql:5.6"
        restart: always
        environment:
          TZ: 'Asia/Shanghai'
          MYSQL_DATABASE: meedu
          MYSQL_ROOT_PASSWORD: 'root'
        volumes:
          - /opt/meedu/mysql:/var/lib/mysql
        networks:
            - backend              
networks:
    frontend:
    backend:
